import type {Metadata} from "next";
import "../globals.css";
import {ThemeProvider} from "@/providers/ThemeProvider";
import Header from "@/components/shared/header/Header";
import ProviderQuery from "@/providers/ProviderQuery";
import ToastProvider from "@/providers/ToastProvider";

export const metadata: Metadata = {

    title: "Pizza clone",
    description: "Generated by create next app",
};

export default function RootLayout({children, modal,}: Readonly<{ children: React.ReactNode; modal: React.ReactNode; }>) {
    return (
        <>
        <ThemeProvider
            attribute="class"
            enableSystem
            disableTransitionOnChange
            defaultTheme={'light'}>
            <ProviderQuery>
                <Header/>
                <ToastProvider>
                <main className={'min-h-screen'}>
                    {children}
                </main>
                </ToastProvider>
                {modal}
            </ProviderQuery>
        </ThemeProvider>
        </>
    );
}
