import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import "../globals.css";
import {ThemeProvider} from "@/providers/ThemeProvider";
import Header from "@/components/shared/header/Header";

const nunito = Nunito({
    subsets: ["cyrillic"],
    variable: '--font-nunito',
    weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning lang="ru">
        <body className={nunito.className}>
        <ThemeProvider
            attribute="class"
            enableSystem
            disableTransitionOnChange
            defaultTheme={'light'}
        >
            <Header />
            <main  className={'min-h-screen'}>
                {children}
            </main>
        </ThemeProvider>
        </body>
        </html>
    );
}
