import { ThemeProvider } from "@/providers/ThemeProvider"
import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "../globals.css"

import Sidebar from "@/components/sidebar/Sidebar"
import ProviderQuery from "@/providers/ProviderQuery"
import ToastProvider from "@/providers/ToastProvider"

const nunito = Nunito({
    subsets: ["cyrillic"],
    variable: '--font-nunito',
    weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <>
        <ThemeProvider
            attribute="class"
            enableSystem
            disableTransitionOnChange
            defaultTheme={'light'}
        >
            <ProviderQuery>
                <ToastProvider>
                    <div className={'flex gap-x-6 '}>
                        <Sidebar/>
                    <main className={'min-h-screen w-full p-1 '}>
                        {children}
                    </main>
                    </div>
                </ToastProvider>
            </ProviderQuery>
        </ThemeProvider>
        </>

    );
}
