import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import "../globals.css";
import {ThemeProvider} from "@/providers/ThemeProvider";
import Header from "@/components/shared/header/Header";
import ProviderQuery from "@/providers/ProviderQuery";
import {ToastContainer} from "react-toastify";
import ToastProvider from "@/providers/ToastProvider";
import Sidebar from "@/components/sidebar/Sidebar";

const nunito = Nunito({
    subsets: ["cyrillic"],
    variable: '--font-nunito',
    weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <>
        <ThemeProvider
            attribute="class"
            enableSystem
            disableTransitionOnChange
            defaultTheme={'light'}
        >
            <ProviderQuery>
                <ToastProvider>
                    <div className={'flex gap-x-6 '}>
                        <Sidebar/>
                    <main className={'min-h-screen w-full p-1 '}>
                        {children}
                    </main>
                    </div>
                </ToastProvider>
            </ProviderQuery>
        </ThemeProvider>
        </>

    );
}
